version: '1.0'

services:
  backend:
    user: root
    build: .
    container_name: course_management
    ports:
      - '9000:9000' # Your NestJS app port
    env_file:
      - .env
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=12345
      - DATABASE_NAME=course_management
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules

    command: npm run start:dev

  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    ports:
      - '13333:5432' # Map host port 5333 to container's 5432 (Postgres default)
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: course_management

volumes:
  pgdata:
